steps:
  # Build the React application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
    dir: '.'

  # Build for production
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: '.'

  # Serve with a simple HTTP server
  - name: 'node:18'
    entrypoint: 'npx'
    args: ['http-server', 'dist', '-p', '8080', '-a', '0.0.0.0']
    dir: '.'

  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/scribe-frontend:$COMMIT_SHA', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/scribe-frontend:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'scribe-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/scribe-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '20'

# Store images
images:
  - 'gcr.io/$PROJECT_ID/scribe-frontend:$COMMIT_SHA'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_4'
